name: Deploy User Site

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Kullanıcının GitHub Adı'
      filePath:
        description: 'Yüklenen Dosya Yolu'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Upload to User Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.event.inputs.username }}
          FILE_PATH: ${{ github.event.inputs.filePath }}
        run: |
          curl -X PUT -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary @${FILE_PATH} \
            https://api.github.com/repos/${USERNAME}/${USERNAME}.github.io/contents/index.html
